### ISSUE TITLE
Put the output file into /tmp/source-route folder if in rails application

### ISSUE THREAD

**Issue by brookzhang** [raykin/source-route#4]
It will be more convenient if do so.

**Comment by raykin** [comment]
Try this 
    SourceRoute.enable do
      method_id :wanted_method_name
      filename 'tmp/source-route.html'
    end
Make sure you're using the latest version.
Btw, the gem is for general usage, not rails specific, there may be no tmp folder in some case, so it's better to leave the user decide where to save the output file.
